lab3cc:main.o Member.o MemberList.o MemberTester.o MemberListTester.o
	g++ main.o Member.o MemberList.o MemberTester.o MemberListTester.o -o lab3cc
main.o:main.cpp
	g++ -c main.cpp
Member.o:Member.cpp
	g++ -c Member.cpp
MemberList.o:MemberList.cpp
	g++ -c MemberList.cpp
MemberTester.o:MemberTester.cpp
	g++ -c MemberTester.cpp
MembeListTester.o:MembeListTester.cpp
	g++ -c MembeListTester.cpp
