lab3cc:main.o Book.o BookList.o BookTester.o BookListTester.o
	g++ main.o Book.o BookList.o BookTester.o BookListTester.o -o lab3cc
main.o:main.cpp
	g++ -c main.cpp
Book.o:Book.cpp
	g++ -c Book.cpp
BookList.o:BookList.cpp
	g++ -c BookList.cpp
BookTester.o:BookTester.cpp
	g++ -c BookTester.cpp
BookListTester.o:BookListTester.cpp
	g++ -c BookListTester.cpp
